name: tpdart
description: Mon projet Dart sans création automatique
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.8.0'

dependencies:
  emoji_extension: ^1.2.0
  interact: ^2.2.0
  # Ajoute ici tes packages si nécessaire
